### ISSUE TITLE
Delightful project ... quick question(s)

### ISSUE THREAD

**Issue by RandoSY** [jamesbowman/spidriver#1]
Hello!

Just wondering when you were going to follow up you introductory video (FEB SVFIG), and further clarify/share the amazing SiLab EFM8 My-forth tool-chain you built for this project? 

Are your plans still on track to crowdfund your SPI monitor? Thanks for all your hard work on this!

Randy

**Comment by jamesbowman** [comment]
Hi Randy,

Talking at June Svfig: definitely maybe. I'm not 100% sure I can attend Saturday.

The SPIDriver will launch in a few days. So many fingers are crossed. Please tell anyone who might be interested -- thanks!

**Comment by RandoSY** [comment]
James,

 

150$ funded in TWO DAYS? Wow, you sir, are the man!

 

I will hope you share you tool set along the way J Gotta be some awesome real time performance in your rig…

 

Best,

 

Randy

**Comment by jamesbowman** [comment]
Never did make it to the SVfig meeting... maybe Forth day 2018 in November!
