### ISSUE TITLE
All indicators colored bars full all the times.

### ISSUE THREAD

**Issue by kirill-chilingarashvili** [jamesbowman/spidriver#13]
I just had a chance to test a device,
The voltage above and current indicators work as expected,
bu all of
- SCK
- MISO
- MOSI
- CS
- A
- B

bars are filled with color all the time.
I tried to follow the tutorials - the border around CS, A symbols blink, but the bars designated to show signal are filled all the time.
I tried the image rendering (TFT demo) sample, and the TFT is white and bars are filler.

I am sorry for noob question -  really just got my SPIDriver and tried to follow the tutorials

Can you please help me - where to start debugging this

**Comment by jamesbowman** [comment]
Definitely sounds like a hardware issue. Email me at jamesb@excamera.com to arrange a replacement.
