### ISSUE TITLE
Passive monitoring?

### ISSUE THREAD

**Issue by osterwood** [jamesbowman/spidriver#2]
In the future, could the SPI Driver be used to monitor traffic between an external SPI master and slave? 

In this mode, I’d love to set a target byte sequence / trigger via the API and a number of bytes to read out once that trigger is seen.  Or the hardware could just provide a continuous stream of data to the computer and triggering / masking could happen there.

**Comment by jamesbowman** [comment]
On "must have" list for next version. Closing.

**Comment by jml9904** [comment]
This would still be a wonderful thing to have. Especially if it could be done in code and retrofitted to existing units.
